### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by leaf456** [CloneTrooper1019/Roblox-PNG-Library#3]
Can't find any documentation for this project, you should probably create some documentation.

**Comment by WordReaper** [comment]
Pretty simple if you ask me.
`local image = require(PNG).new(png_contents)
image:GetPixel(x,y)`

png_contents = game:GetService("HttpService"):GetAsync("IMAGELINK")

**Comment by leaf456** [comment]
Thanks, I'll close the issue.
